config/routes.rb
Rails.application.routes.draw do
 # resources :carts
  devise_for :users
  get 'profile' => 'users#profile', as: :profile
  post 'jobs/:job_id/apply' => 'applied_jobs#create', as: :apply_to_job
  resources :applied_jobs, only: [:index, :create]
  resources :jobs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/applied_jobs/:id', to: 'jobs#show'
  #when login is clicked on hompate --> takes you to login page
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :applied_job, dependent: :destroy
	before_destroy :ensure_not_referenced_by_any_applied_job
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"} 
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	# private

	# 	def ensure_not_referenced_by_any_applied_job
	# 		unless applied_jobs.empty?
	# 			errors.add(:base, 'Applied Jobs Present')
	# 			throw :abort
	# 		   end
	# 		  end

	end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:role, :project, :description)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :job_role %>
  </div>

  <div class="field">
    <%= form.label :project %>
    <%= form.text_field :project, id: :job_project %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<body class="job_details">
<div class="job_details_header">
	<h1>Job Details</h1>
</div>
<div class="job_details_section">
  <strong>Role:</strong>
  <%= @job.role %>
</p>

<p>
  <strong>Project:</strong>
  <%= @job.project %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>
<%= link_to 'Back', jobs_path %> |
<%= link_to 'Apply', apply_to_job_path(@job), method: :post %>
</div>
</body>