config/routes.rb
Rails.application.routes.draw do
 # resources :carts
  devise_for :users
  get 'profile' => 'users#profile', as: :profile
  post 'jobs/:job_id/apply' => 'applied_jobs#create', as: :apply_to_job
  resources :applied_jobs, only: [:index, :create]
  resources :jobs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/applied_jobs/:id', to: 'jobs#show'
  #when login is clicked on hompate --> takes you to login page
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
	belongs_to :user
	belongs_to :job
	#belongs_to :cart
	has_many :job_items

	def add_job(job_params)
		AppliedJob.applied 
		
		current_user.applied_jobs.where(status: :applied)

		current_item = job_items.find_by(job_id: job_params[:job][:job_id])

	if current_item
		current_item.quantity += job_params[:job][:quantity].to_i
		current_item.save
	else
		new_item = applied_job_items.create(job_id: job_params[:job][:job_id], quantity: job_params[:job][:quantity],
		applied_job_id: self.id)
	end
	 new_item
 end
end

app/controllers/applied_jobs_controller.rb
class AppliedJobsController < ApplicationController
  before_action :set_applied_job, only: [:show, :edit, :update, :destroy]

  # GET /applied_jobs
  # GET /applied_jobs.json
  def index
    @applied_jobs = current_user.applied_jobs #AppliedJob.all
  end

  # GET /applied_jobs/1
  # GET /applied_jobs/1.json
  def show
    @applied_job = AppliedJob.find(params[:id])
  end

  # GET /applied_jobs/new
  def new
    @applied_job = AppliedJob.new
  end

  # GET /applied_jobs/1/edit
  def edit
  end

  # POST /applied_jobs
  # POST /applied_jobs.json
  def create
    @applied_job = AppliedJob.new(job_id: params[:job_id], user_id: current_user.id)

    respond_to do |format|
      if @applied_job.save
        format.html { redirect_to applied_jobs_path, notice: 'Applied job was successfully created.' }
        format.json { render :show, status: :created, location: @applied_job }
      else
        format.html { render :new }
        format.json { render json: @applied_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applied_jobs/1
  # PATCH/PUT /applied_jobs/1.json
  def update
    respond_to do |format|
      if @applied_job.update(applied_job_params)
        format.html { redirect_to @applied_job, notice: 'Applied job was successfully updated.' }
        format.json { render :show, status: :ok, location: @applied_job }
      else
        format.html { render :edit }
        format.json { render json: @applied_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_jobs/1
  # DELETE /applied_jobs/1.json
  def destroy
    @applied_job.destroy
    respond_to do |format|
      format.html { redirect_to applied_jobs_url, notice: 'Applied job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applied_job
      @applied_job = AppliedJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applied_job_params
      params.require(:applied_job).permit(:resume, :cover_letter, :text)
    end
end

app/helpers/applied_jobs_helper.rb
module AppliedJobsHelper
end

app/views/applied_jobs/_form.html.erb
<%= form_with(model: applied_job, local: true) do |form| %>
  <% if applied_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applied_job.errors.count, "error") %> prohibited this applied_job from being saved:</h2>

      <ul>
      <% applied_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :project %>
    <%= form.text_area :project, id: :applied_job_project %>
  </div>
 <div class="field">
    <%= form.label :resume %>
    <%= form.text_area :resume, id: :applied_job_resume %>
  </div>

  <div class="field">
    <%= form.label :cover_letter %>
    <%= form.text_field :cover_letter, id: :applied_job_cover_letter %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :applied_job_user_id %>
  </div>
  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id, id: :applied_job_job_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applied_jobs/edit.html.erb
<h1>Editing Applied Job</h1>

<%= render 'form', applied_job: @applied_job %>

<%= link_to 'Show', @applied_job %> |
<%= link_to 'Back', applied_jobs_path %>

app/views/applied_jobs/index.html.erb
<body class="Applied_Jobs">
<p id="notice"><%= notice %></p>

<h1>Your Job History</h1>

<table div="applied_job_table">
  <thead>
    <tr>
      <th>Resume</th>
      <th>Cover letter</th>
      <!-- <th>Job ID</th>
      <th>User ID</th> -->
      <th>Project</th>
       <th colspan="5"></th>
    </tr>
  </thead>
<tbody>
    <% @applied_jobs.each do |applied_job| %>
      <tr>
        <td><%= applied_job.user.resume %></td>
        <td><%= applied_job.user.cover_letter %></td>
        <!-- <td><%= applied_job.job_id %></td>
        <td><%= applied_job.user_id %></td> -->
        <td><%= applied_job.job.project %></td>
        <td><%= applied_job.user.email %></td>
        <td><%= link_to 'Show', applied_jobs_path %></td>
        <!-- <td><%= link_to 'Edit', edit_job_path(applied_job) %></td> -->
      <!--   <td><%= link_to 'Destroy', applied_jobs_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applied Job', new_job_path %>
</body>

app/views/applied_jobs/new.html.erb
<h1>New Applied Job</h1>

<%= render 'form', applied_job: @applied_job %>

<%= link_to 'Back', applied_jobs_path %>

app/views/applied_jobs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Resume:</strong>
  <%= @applied_job.user.resume %>
</p>

<p>
  <strong>Cover letter:</strong>
  <%= @applied_job.user.cover_letter %>
</p>

<p>
  <strong>Text:</strong>
  <%= @applied_job.text %>
</p>

<%= link_to 'Edit', edit_applied_job_path(@applied_job) %> |
<%= link_to 'Back', applied_jobs_path %>